aspirepress/aspireupdate

- README.md
- aspirepress-updater.php
- assets/css/aspirepress.css
- assets/js/aspirepress.js
- classes/AspirePress_AdminSettings.php
- classes/AspirePress_Debug.php
> The Admin UI

- assets/css/aspirepress.css
- assets/images/icon-key.svg
- assets/js/aspirepress.js
- classes/AspirePress_AdminSettings.php
- classes/AspirePress_Utils.php
Fetch API Key from API
PS : API currently Hard code to "api.aspirepress.org/repository/api/v1/apitoken"
Allow user to pull the API key seamlessly
By opening this pull request, I do agree to abide by the [CODE OF CONDUCT](CODE_OF_CONDUCT.md) and be bound by the terms
of the [Contribution Guidelines](CONTRIBUTING.md) in effect on the date and time of my contribution as proven by the
or entity, and …
> Fetch API Key from API

- aspirepress-updater.php
- assets/css/aspirepress.css
- assets/images/icon-key.svg
- assets/js/aspirepress.js
- classes/AspirePress_AdminSettings.php
- classes/AspirePress_Debug.php
- classes/AspirePress_Utils.php
Right into business, Not using any of the classes.
This is for proof of concept.
or …
> Precedural

- aspirepress-updater.php
- assets/css/aspirepress.css
- assets/images/icon-key.svg
- assets/js/aspirepress.js
- classes/AspirePress_AdminSettings.php
- classes/AspirePress_Debug.php
- classes/AspirePress_Utils.php
---------
* Fetch API Key from API
PS : API currently Hard code to "api.aspirepress.org/repository/api/v1/apitoken"
* Changing the URL for the rewrite
* Take over the Filter
fixing it to work!
Further, I certify that this work is my own, is …
> Precedural (#11)

- aspirepress-updater.php
- classes/AspirePress_AdminSettings.php
- classes/AspirePress_ApiWordpressOrgRewriteRule.php
Fixing ssl verification and debugging issues
or entity, and I am not violating any license agreements or contracts I have …
> Making main playground ready 

- README.md
- aspire-update.php
Fix minimum PHP and WP requirement to align to WP support for 7.4 in plugin and README
as per issue #30 
not functional
or …
> Fix minimum PHP and WP requirement to align to WP support for 7.4

- README.md
- assets/playground/blueprint.json
README update for 0.5
because the UI changed and several config parameters did as well
not fixes but rather a simplified UI for adding rewrites
Further, I certify that this work is my own, is original, does not violate the intellectual property …
> Readme updates for 0.5

- README.md
- assets/playground/blueprint.json
- readme.txt
updated README.md and readme.txt
post plugin-check changes and typos in README.md added Playgrounds link
no
or entity, and I …
> Playground ready

- README.md
- assets/playground/blueprint.json
- includes/class-api-rewrite.php
- readme.txt
pull in most recent changes from main branch
continue to sync the playground-ready branch with changes made in main
see main for PRs committed
Further, I certify that this work is my own, is original, does not violate the intellectual property …
> Update playground-ready branch from main

- README.md
- assets/playground/blueprint.json
- readme.txt
removed duplicate debug log section in readme, removed ask for UI updates (this whole section should be removed from README eventually)
typos and more clarity
none
Further, I certify that this work is my own, is original, does not violate the …
> More README updates for 0.5

- includes/class-api-rewrite.php
---------
updating playground-ready with changes from PR #69 
bug filed 
reference PR #69 
or entity, and I am not violating …
> Prevent Recursion on certain Host name patterns (#69)

- assets/playground/blueprint.json
- includes/class-api-rewrite.php
- includes/class-controller.php
- includes/class-plugins-screens.php
- includes/class-themes-screens.php
changes on main being pulled into playground-ready
normal course of actions
I think eventually this could be a process that is automated with resolve conflicts to be set as exceptions for continuous integration and  deployment
Further, I certify …
> pull in most recent changes on main into playground-ready

- .github/workflows/phpunit-tests.yml
- .gitignore
- bin/install-wp-tests.sh
- composer.json
- composer.lock
- phpunit.xml.dist
- tests/AdminSettings/AdminSettings_GetSettingTest.php
- tests/bootstrap.php
This adds:
- PHPUnit scaffolding (courtesy of WP-CLI)
- Composer files for dependency management (`composer install`) and a script for testing (`composer run test`).
We had no setup for unit testing.
Fixes #63
Further, I certify that this work …
> Add PHPUnit.

- .github/workflows/phpunit-tests.yml
- The PHP version is now correctly being taken from the matrix.
- `push` and `workflow_dispatch` workflow triggers have been added.
- The PHP version was incorrectly referencing `$` and causing an error.
- The `pull_request` workflow trigger was too limited.
Fixes #91
version in effect on the date and time of this pull request, or any future revisions for pull …
> `Workflows`: Fix PHP version and add more workflow triggers.

- assets/js/aspire-update.js
Fixes Settings not getting saved when rewrites were turned off
Fixes Settings not getting saved when rewrites were turned off
Fixes #103
Fixes #43
Further, I certify that this work is my own, is original, does not violate the intellectual …
> Fixes Settings not getting saved when rewrites were turned off

- includes/class-admin-settings.php
Fixes #110
(Please list the changes you made...)
(Please list the reasons you made the changes...)
Further, I certify that this work is my own, is original, does not violate the intellectual property of …
> Make the api key allow empty values for now

- includes/class-themes-screens.php
- Nonce verification has been added to `\AspireUpdate\Themes_Screens::redirect_to_theme_install()`.
- `$_REQUEST/$_GET` values are sanitized.
Plugin Check raised flags for missing nonce verification and input sanitization.
Note that this may be a [known issue](https://wordpress.org/support/topic/getting-nonce-verification-needed-for-every-instance-of-a-_get-or-_request-var/) with Plugin Check and/or WordPress Coding Standards. Nevertheless, this Pull Request adds nonce verification and input sanitization for safety.
Fixes #107 
of the [Contribution Guidelines](https://github.com/aspirepress/.github/CONTRIBUTING.md) in effect on the …
> `Themes_Screens`: Add nonce verification and sanitize `$_REQUEST/$_GET` values.

- includes/class-admin-settings.php
Added back the `esc_html__()`
(Please list the changes you made...)
Accidentally removed in #102 
or entity, and I am not …
> oops, accidentally deleted

- .editorconfig
`.editorconfig` was added.
To make file formatting consistent.
Fixes #86
or entity, and I am not violating any license …
> Add `.editorconfig`.

- LICENSE.md
- aspire-update.php
- composer.json
- readme.txt
Added License File
Added License File
Added License File
#68
or entity, and I am not violating any license agreements or …
> Added License File

- assets/css/aspire-update.css
- includes/class-admin-settings.php
- includes/class-controller.php
- tests/bootstrap.php
1) Hide Voltron on Mobile
2) Newly installed coding standards fixed several CS issues.
1) Hide Voltron on Mobile as it was not rendering correctly due to low space
2) Newly installed coding standards fixed several CS issues - CS run automated formatting fixes
#122 
version in effect on the date and time of this pull request, or any future revisions for pull …
> #122 Hide on Mobile

- languages/AspireUpdate-es_ES.po
Added Spanish translation
Added Spanish .po file
or entity, and I am not violating …
> Adding new Spanish translation

- languages/AspireUpdate-es_ES.po
Added missing strings
(Please list the reasons you made the changes...)
or entity, …
> Updating Spanish translations

- languages/AspireUpdate-ca_ES.po
Added translations for Catalan language.
Translation to Catalan language was not available.
Just added the translation.
By opening this pull request, I do agree to abide by the [CODE OF CONDUCT](https://github.com/aspirepress/.github/CODE_OF_CONDUCT.md) and be bound by the terms of the [Contribution Guidelines](https://github.com/aspirepress/.github/CONTRIBUTING.md) in effect on the date and time of my contribution as proven by the revision information in GitHub. I also agree that any previous contributions shall be deemed subject to the terms of the ersion in effect on the date and time of this pull request, or any future revisions for pull requests I may submit.
Further, I certify that this work is my own, is original, does not violate the intellectual property of any other person or …
> Add Catalan translation

- aspire-update.php
- readme.txt
Preparing for 0.6 Release
Preparing for 0.6 Release.
Change log updated.
Update version numbers to prepare for 0.6 release.
None
> Preparing for 0.6 Release

- .github/ISSUE_TEMPLATE/BugReport.yml
- .github/workflows/playground-blueprint.yml
- README.md
- aspire-update.php
- composer.json
- languages/aspireupdate.pot
Fixes remaining references to mixed case `aspirepress/AspireUpdate` to `aspirepress/aspireupdate`.
> update referenced to mixed case repository

- .github/workflows/generate-pot.yml
- composer.json
Added a GitHub Action to generate a POT file on a tagged release
Fixes https://github.com/aspirepress/aspireupdate/issues/195
> add GA to generate POT on tag/release

- README.md
added change log
README should have a changelog
eventually we will support defacto CHANGELOG format, but not yet....
> added changelog

- .github/workflows/generate-pot.yml
remove feature branch once merged
> run GA on push to `main` and feature branch

- tests/phpunit/tests/PluginsScreens/PluginsScreens_GetInstanceTest.php
- Added tests for `Plugins_Screens::get_instance()`
See #216 
> Add tests for `Plugins_Screens::get_instance()`

- tests/phpunit/tests/ThemesScreens/ThemesScreens_GetInstanceTest.php
- Added tests for `Themes_Screens::get_instance()`
See #216 
> Add tests for `Themes_Screens::get_instance()`

- includes/class-admin-settings.php
- includes/class-api-rewrite.php
- includes/class-controller.php
1) Change the API URL everywhere
2) Add API Auth header
3) Add Cache Buster to URLs to help with AC debugging
Preparing plugin for V 0.6 for beta Testing
1) Change the API URL everywhere
2) Add API Auth header
3) Add Cache Buster to URLs to help with AC debugging
> Change the API URL and add more debugging options

- includes/class-admin-settings.php
Add aspirecloud.io endpoint for testing
Add aspirecloud.io endpoint for bleeding edge testing
Add aspirecloud.io in addition to aspirecloud.net as endpoints to help with testing the latest versions
#285 
> Add aspirecloud.io endpoint for testing

- README.md
Updated the `README.md` note about the menu location.
The menu location changed from `Dashboard > AspireUpdate` to `Settings > AspireUpdate`.
Fixes #210 
> README: Update note about the menu location.

- assets/js/aspire-update.js
Debug Field Validation
Fixes URL Validation in Other Hosts Field.
The Other Hosts Field was always validating to wrong once a wrong URL is entered even after fixing the wrong URL.
Fixes #311 
> Debug Field Validation

- aspire-update.php
- readme.txt
0.6.2 Prep
0.6.2 Tag Prep
0.6.2 Tag Prep
No
> 0.6.2 Prep

- aspire-update.php
- readme.txt
Bumps version to 0.9 so we can cut a new release.
Need a new release so we have a usable download artifact.
none.
> build: bump to version 0.9

- aspire-update.php
- readme.txt
* Bumped version to 0.9.1 in all _three_ places it needed.  oopsie.
* Waiting to tag til after merge.  oopsie.
oopsie.
nopesie.
> release 0.9.1 (for realsies!)

- CHANGES.md
- readme.txt
> move changelog to CHANGES.md

- aspire-update.php
- package.json
- readme.txt
Update Plugin Version to 0.9.2 to check new Workflow
Update Plugin Version to 0.9.2
Update Plugin Version to 0.9.2 to test tagging a new release
None
> Update Plugin Version to 0.9.2

- composer.lock
- vendor/afragen/translations-updater/CHANGES.md
- vendor/afragen/translations-updater/composer.json
- vendor/afragen/translations-updater/src/Translations_Updater/API.php
Just a `composer update`
update for `afragen/translations-updater`
nope
> composer update to fix small issue in translations-updater

- aspire-update.php
- package.json
- readme.txt
V 0.9.3 Prep
(Please list the changes you made...)
(Please list the reasons you made the changes...)
> V 0.9.3 Prep

- assets/js/aspire-update.js
Previously, when clearing the log or encountering an error viewing the log, a message would appear in an alert. This change generates admin notices instead.
The notice when clearing the log, and the notice when viewing a log, each have their own ID. Repeated clicks of a button will simply replace the existing respective notice to avoid notice spam.
---
A new JS class, `AdminNotice` has been added to the codebase.
It has one `static` method, `add(string message, object args)`, where `args` has the following supported keys:
- `(string) type` - This is appended to a `notice-` class prefix. Common values: `'success'`, `'error'`, or `'info'`
- `(bool) dismissible` - Whether the notice is dismissible. Defaults to `true`.
- `(string) id` - The ID for the notice. If a second notice is added with …
> Admin_Settings: Display notices instead of alerts when managing the log.

- aspire-update.php
- assets/css/aspire-update.css
- assets/js/aspire-update.js
- composer.lock
- hosts.json
- includes/class-admin-settings.php
- includes/class-branding.php
- includes/class-utilities.php
- readme.txt
- tests/phpunit/tests/Utilities/Utilities_GetHostsDataTest.php
Moved the Hosts Data outside the codebase to make it easier for federated repos to add new hosts if required without having to edit plugin files.
To have a single location to edit the Hosts as well as to make it easier to less technical people to add or remove hosts.
#394 
> Hosts.json File for Hosts Data

- CHANGES.md
- aspire-update.php
- languages/aspireupdate.pot
- package-lock.json
- package.json
- readme.txt
- The plugin's version has been updated in the following files:
- `aspireupdate.php`
- `readme.txt`
- `package.json` (and `package-lock.json`)
- `languages/aspireupdate.pot`
- The POT file has been updated with the newest strings.
- Changelogs have been added for versions 0.9.2 - 0.9.4.
**N.B. When merging, this PR should be squashed and merged.**
- In preparation for the 0.9.4 release.
Fixes #376
By opening this pull request, I do agree to abide by the [Code of Conduct](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CODE_OF_CONDUCT.md) and be bound by the terms of the [Contribution Guidelines](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CONTRIBUTING.md) in effect on the date and time of my contribution as proven by the revision …
> Release: Bump the plugin version, add a changelog, and update the POT file for 0.9.4.
