assets/css/aspirepress.css
classes/AspirePress_AdminSettings.php

1) Added Reset Button
2) Added Advanced mode for the plugin UI which can be accessed by added "&advanced=true" to the plugin settings page URL.  This will reveal the full feature set.
3) Defaults to the aspirepress API once activated
Advanced and Normal Mode for Plugin to avoid confusing casual users
By opening this pull request, I do agree to abide by the [CODE OF CONDUCT](CODE_OF_CONDUCT.md) and be bound by the terms
of the [Contribution Guidelines](CONTRIBUTING.md) in effect on the date and time of my contribution as proven by the
version in effect on the date and time of this pull request, or any future revisions for pull …

Advanced and Normal Mode for Plugin

---

aspirepress-updater.php
classes/AspirePress_ApiWordpressOrgRewriteRule.php

* Removing the plugin functionality being contingent on ssl verify being off
* Removing an exclusion for plugin checking that was accidentially left in from debugging
This makes the plugin work (sort of)
Further, I certify that this work is my …

Adjusting the `main` branch so that the plugin functions properly

---

README.md
assets/playground/blueprint.json
readme.txt

add WP Playground link in readme
playground-ready branch contains the currently stable version to be experimented with on docs.aspirepress.org
none
Further, I certify that this work is my own, is original, does not violate the intellectual …

WP Playground  link in README, added readme.txt for plugin-check

---

includes/class-api-rewrite.php

A space was removed before the colon `:`, and one added after it.
The colon `:` is part of the message, but was displaying as part of the URL.
fixes #52 
Further, I certify that this work is my own, is original, does not violate the intellectual …

Adjust spacing around colon in rewrite debug messages.

---

README.md

Removing a space from the:
```php
// Works as of PHP 7
define('AP_DEBUG_TYPES ', array(
'string', 'request', 'response'
));
```
Removing a space from the example code of AP_DEBUG_TYPES
As its a example it should be correct so its works directly to copy it.
(https://github.com/aspirepress/AspireUpdate/issues/54)
version in effect on the date and time of this …

Update README.md - removing a space from the example code.

---

includes/class-controller.php
includes/class-plugins-screens.php

- Added a new class: `\\AspireUpdate\Plugins_Screens`.
- Added conditional removal of 'Featured' and 'Favorites' tabs when API rewrite is enabled.
These tabs are not served by the rewritten API.
fixes #74 
Further, I certify that this work is my …

`Add New Plugin`: Remove 'Featured' and 'Favorites' tabs when API rewrite is enabled.

---

includes/class-controller.php

- Initialize `Plugins Screens` in `Controller::__construct()`.
The initialization was added in [94e732e](https://github.com/aspirepress/AspireUpdate/commit/94e732ec1d5556b45344f62c36105afbaf260207), but was accidentally removed when merging [7336a51](https://github.com/aspirepress/AspireUpdate/commit/7336a51d490ac8dad594855026ef2279f9241805).
Fixes #88  …

`Plugins Screens`: Initialize in `Controller::__construct()`.

---

aspire-update.php
tests/AdminSettings/AdminSettings_GetSettingTest.php
tests/bootstrap.php

1. The instantiation of `\AspireUpdate\Controller` is guarded so that it doesn't run when the tests are running.
2. A new object is used for each test so that state doesn't spill into other tests.
`\AspireUpdate\Controller` was instantiated in the main plugin file.
This affected test runs because options were already set.
Fixes #94 
version in effect on the …

`Tests`: Ensure options are not set when tests run.

---

includes/class-debug.php

Fixes Warning when debug-aspire-update.log doesnt exist
Fixes Warning when debug-aspire-update.log doesnt exist
Fixes #57
or …

Warning when debug-aspire-update.log doesnt exist

---

.gitignore
phpunit.xml.dist

- A `<coverage>` element was added to `phpunit.xml.dist`.
- The coverage directory defaults to `/tests/coverage`.
- The test cache directory defaults to `/tests/cache`.
- The `/tests/coverage` and `/tests/cache` directories have been added to `.gitignore`.
- Only the main plugin file and "code-only" files in the `includes` directory are included in coverage reports.
- `includes/autoload.php` is excluded from coverage reports.
Running coverage reports can be cumbersome for experienced and inexperienced users.
This makes it much more convenient to run a coverage report when writing tests to ensure the tests are covering the expected portions of code.
Fixes #96 
the [CODE OF CONDUCT](https://github.com/aspirepress/.github/CODE_OF_CONDUCT.md …

`Tests`: Add default coverage settings.

---

aspire-update.php
includes/class-admin-settings.php

- `\AspireUpdate\Admin_Settings` has a new method: `::delete_all_settings()`. This method is multisite-safe.
- `aspire-update.php`:
- Registers an activation hook which performs a once-per-activation registration of an uninstall hook.
- The activation hook is used to avoid registering the same uninstall hook on every load.
- The uninstall hook calls the new `\AspireUpdate\Admin_Settings::delete_all_settings()` method when the plugin is uninstalled.
Settings were persisting in the database after the plugin was uninstalled. We should clean up after ourselves.
Fixes #101
of the [Contribution …

`Admin Settings`: Delete all settings when the plugin is uninstalled.

---

.gitattributes
.github/workflows/releases.yml

Added `.gitattributes` file to ignore specific files during a zip download.
Added a GitHub Action to create a zip file release asset with each new tagged release.
This is the same process I've been using with Git Updater for a while now.
https://github.com/afragen/git-updater/releases/tag/12.6.0
Fixes #120 
Nothing broken, just better.
version in effect on the …

create zip with each new tagged release

---

assets/js/aspire-update.js
includes/class-admin-settings.php
includes/class-controller.php
tests/bootstrap.php

1) #128 Make the API Key Error Translatable
2) Coding Standards auto update, this should stop once one of the newer PRs are merged.
Make the API Key Error Message Prefix Translatable
#128 
Further, I certify that this work is my own, is …

#128 Make the API Key Error Translatable

---

includes/class-admin-settings.php

1. A check was added to ensure `$_POST['aspireupdate_settings']` is set.
2. A `// phpcs:ignore <sniff> -- <explanation>` comment was added.
- The contents of `$_POST['aspireupdate_settings']` are sanitized in `AspireUpdate\Admin_Settings::sanitize_settings()`.
- **Such comments should be used extremely rarely.**
- While we could add a `rule.properties.property.element` entry to `phpcs.xml.dist` to denote this as a custom sanitizing function, it appears that PCP doesn't take this into consideration. Therefore, an ignore comment seems appropriate here.
PCP was showing warnings from the "Plugin Repo" checks.
Fixes #132 
of the …

Resolve PCP security warnings in `AspireUpdate\Admin_Settings::update_settings()`.

---

.github/workflows/releases.yml

Rename zip from AspireUpdate to aspire-update. Better conforms to dot org naming guidelines.
Related #120 
or entity, and I …

rename from AspireUpdate to aspire-update

---

assets/playground/blueprint.json

Added a step to remove the hello dolly plugin 
The plugin is a bit annoying so I wanted to remove it 
not really 
@costdev basically told me how to do this! Thanks :-) 
By opening this pull request, I do agree to abide by the [CODE OF CONDUCT](https://github.com/aspirepress/.github/CODE_OF_CONDUCT.md) and be bound by the terms of the [Contribution Guidelines](https://github.com/aspirepress/.github/CONTRIBUTING.md) in effect on the date and time of my contribution as proven by the revision information in GitHub. I also agree that any previous contributions shall be deemed subject to the terms of the version in effect on the date and time of this pull request, or any future revisions for pull requests I may submit.
Further, I certify that this work is my own, is original, does not violate …

Remove plugin hello dolly

---

.github/workflows/playground-blueprint.yml

- The `write` permission has now been added to the Playground blueprint workflow.
githubactions[bot] didn't have sufficient permission to perform the required actions.
Fixes #141 
By opening this pull request, I do agree to abide by the [CODE OF CONDUCT](https://github.com/aspirepress/.github/CODE_OF_CONDUCT.md) and be bound by the terms of the [Contribution Guidelines](https://github.com/aspirepress/.github/CONTRIBUTING.md) in effect on the date and time of my contribution as proven by the revision information in GitHub. I also agree that any previous contributions shall be deemed subject to the terms of the ersion in effect on the date and time of this pull request, or any future revisions for pull requests I may submit.
Further, I certify that this work is my own, is original, does not …

Workflows: Add write permission for playground blueprint

---

.github/workflows/playground-blueprint.yml
assets/playground/blueprint.json

- The workflow now only runs on the `aspirepress/AspireUpdate` repository.
- `main` has been removed from the applicable branches for the Playground blueprint workflow.
- The WordPress Playground `blueprint.json` defaults to the `main` branch now, rather than the `playground-ready` branch.
Previously, upon a `push` event to the `main` branch, the Playground blueprint workflow would make a follow-up commit to make the playground branch URL match `main`.
However, the `main` branch is a *protected* branch. This means changes can only be made by Pull Request. Therefore, the workflow cannot make a direct commit.
Since `main` is the only *protected* branch, this should be the default for the Playground blueprint.
Additionally, the workflow ran on the main repository _and_ on forks, creating an …

Have Playground blueprint default to `main`.

---

includes/class-admin-settings.php

Settings Saved Notice
Settings Saved Notice
Add a Settings Saved Notice for clarity
#155 

Settings Saved Notice

---

assets/css/aspire-update.css
assets/js/aspire-update.js
includes/class-admin-settings.php
includes/class-controller.php
includes/class-debug.php
includes/views/page-admin-settings.php

Reverts aspirepress/AspireUpdate#184

Revert "Merge Main into Translations"

---

composer.lock
vendor/afragen/translations-updater/CHANGES.md
vendor/afragen/translations-updater/README.md
vendor/afragen/translations-updater/composer.json
vendor/afragen/translations-updater/src/Translations_Updater/API.php
vendor/afragen/translations-updater/src/Translations_Updater/Language_Pack.php
vendor/afragen/translations-updater/src/Translations_Updater/Language_Pack_API.php

Added API error caching for 60 min as GitHub API rate limits unauthenticated requests for 60 requests/hour. Leaves an entry in the debug.log

update afragen/translations-updater with error caching/logging

---

.github/workflows/generate-pot.yml

Fixed reference to `varunsridharan/action-wp-pot-generator`
Fixes #203

fix version reference of GA

---

.github/workflows/generate-pot.yml

Changed the version reference of the POT generation action from `@2` to `@2.0`.
The action was failing and its readme states `@2.0`.
Fixes #203 

Set POT generation action version to `2.0`.

---

.github/workflows/generate-pot.yml

Added write permissions for the POT generation workflow.
GitHub Actions bot doesn't have write permissions by default.
Fixes #203 

Add write permissions to POT generation workflow.

---

.gitattributes

Added an `export-ignore` rule for the `.cache` directory in `.gitattributes`.
While this file is needed for development, it should not be included in release builds.
Fixes #189 

Don't export the `.cache` directory.

---

composer.lock
includes/class-admin-settings.php
includes/class-utilities.php

Use the full domain name instead of attempting to extract the top level TLD
Changed behavior of API Key call to use the full domain name instead of trying to extract the top TLD which can lead to parsing issues
Extracting the top TLD was an unnecessary complication which is not required.
Fixes #194 

Use the full domain name

---

phpcs.xml.dist
tests/phpunit/bootstrap.php
tests/phpunit/includes/AdminSettings_UnitTestCase.php
tests/phpunit/tests/AdminSettings/AdminSettings_GetSettingTest.php

- A new unit test case has been introduced: `AdminSettings_UnitTestCase`.
- The new unit test case has been implemented in `AdminSettings_GetSettingTest`.
To reduce repetition and the maintenance burden.
Fixes #212

Introduce and implement `AdminSettings_UnitTestCase`

---

tests/phpunit/tests/API_Rewrite/APIRewrite_ConstructTest.php

- Added tests for `API_Rewrite::__construct()`
See #216 

Add tests for `API_Rewrite::__construct()`

---

tests/phpunit/tests/API_Rewrite/APIRewrite_PreHttpRequestTest.php
tests/phpunit/tests/AdminSettings/AdminSettings_GetSettingTest.php

- Added tests for `API_Rewrite::pre_http_request()`
- Added `@runTestsInSeparateProcesses` and `@preserveGlobalState disabled` annotations to `Admin_Settings::get_setting()` tests to prevent spillage across the test suite.
- To improve PHPUnit test coverage.
- To improve PHPUnit test stability.
See #216 

Add tests for `API_Rewrite::pre_http_request()`

---

includes/class-controller.php
tests/phpunit/tests/Controller/Controller_ConstructTest.php

- Added tests for `Controller::__construct()`
- Added `@codeCoverageIgnore` annotations to:
- `Controller::api_rewrite()`
- `Controller::clear_log()`
- `Controller::read_log()`
See #216 

Add tests for `Controller::__construct()`

---

tests/phpunit/tests/PluginsScreens/PluginsScreens_ConstructTest.php

- Added tests for `Plugins_Screens::__construct()`
See #216 

Add tests for `Plugins_Screens::__construct()`

---

tests/phpunit/tests/PluginsScreens/PluginsScreens_RemoveUnusedFilterTabsTest.php

- Added tests for `Plugins_Screens::remove_unused_filter_tabs()`
See #216 

Add tests for `Plugins_Screens::remove_unused_filter_tabs()`

---

tests/phpunit/tests/ThemesScreens/ThemesScreens_ConstructTest.php

- Added tests for `Themes_Screens::__construct()`
See #216 

Add tests for `Themes_Screens::__construct()`

---

tests/phpunit/tests/ThemesScreens/ThemesScreens_AdminEnqueueScriptsTest.php

- Added tests for `Themes_Screens::admin_enqueue_scripts()`
See #216 

Add tests for `Themes_Screens::admin_enqueue_scripts()`

---

includes/class-themes-screens.php
tests/phpunit/tests/ThemesScreens/ThemesScreens_RedirectToThemeInstallTest.php

- Added tests for `Themes_Screens::redirect_to_theme_install()`
- Added a check so that `exit` is not called during test runs
- Fixed an improper nonce check which previously continued execution even if no nonce was present at all
- To improve PHPUnit test coverage.
- To improve security and ensure tests could pass.
See #216 

Add tests for `Themes_Screens::redirect_to_theme_install()`

---

tests/phpunit/tests/Utilities/Utilities_IncludeFileTest.php

- Added tests for `Utilities::include_file()`
See #216 

Add tests for `Utilities::include_file()`

---

tests/phpunit/tests/Utilities/Utilities_GetSiteDomainTest.php

Added tests for `Utilities::get_site_domain()`
See #216

Add tests for `Utilities::get_site_domain()`.

---

tests/phpunit/tests/AdminSettings/AdminSettings_GetInstanceTest.php

Added tests for `Admin_Settings::get_instance()`
See #216

Add tests for `Admin_Settings::get_instance()`

---

includes/class-admin-settings.php
tests/phpunit/tests/AdminSettings/AdminSettings_ResetSettingsTest.php

- Added tests for `Admin_Settings::reset_settings()`
- Added a check so that exit is not called during test runs.
See #216

Add tests for `Admin_Settings::reset_settings()`

---

tests/phpunit/tests/AdminSettings/AdminSettings_AdminNoticesTest.php

Added tests for `Admin_Settings::admin_notices()`
See #216

Add tests for `Admin_Settings::admin_notices()`

---

includes/class-admin-settings.php
tests/phpunit/includes/AdminSettings_UnitTestCase.php
tests/phpunit/tests/AdminSettings/AdminSettings_UpdateSettingsTest.php

- Added tests for `Admin_Settings::update_settings()`
- Introduced `AdminSettings_UnitTestCase::$options_page`
- Added a check so that exit is not called during test runs
See #216

Add tests for `Admin_Settings::update_settings()`

---

tests/phpunit/tests/AdminSettings/AdminSettings_RegisterAdminMenuTest.php

Added tests for `Admin_Settings::register_admin_menu()`
See #216

Add tests for `Admin_Settings::register_admin_menu()`

---

tests/phpunit/tests/AdminSettings/AdminSettings_AdminEnqueueScriptsTest.php

Added tests for `Admin_Settings::admin_enqueue_scripts()`
See #216

Add tests for `Admin_Settings::admin_enqueue_scripts()`

---

tests/phpunit/tests/AdminSettings/AdminSettings_TheSettingsPageTest.php

Added tests for `Admin_Settings::the_settings_page()`
See #216

Add tests for `Admin_Settings::the_settings_page()`

---

tests/phpunit/tests/AdminSettings/AdminSettings_SanitizeSettingsTest.php

Added tests for `Admin_Settings::sanitize_settings()`
See #216

Add tests for `Admin_Settings::sanitize_settings()`

---

tests/phpunit/tests/AdminSettings/AdminSettings_RegisterSettingsTest.php

Added tests for `Admin_Settings::register_settings()`
See #216

Add tests for `Admin_Settings::register_settings()`

---

phpcs.xml.dist
tests/phpunit/bootstrap.php
tests/phpunit/includes/Debug_UnitTestCase.php
tests/phpunit/includes/class-ap-fake-filesystem.php

- A new unit test case has been introduced: `Debug_UnitTestCase`.
- A fake filesystem class to aid testing has been introduced: `AP_FakeFilesystem`.
- This extends `WP_Filesystem_Direct` and currently overrides the `::exists()`, `::is_readable()`, and `::is_writable()` methods.
- Coding Standards: Some sniffs were previously excluded just for test classes. These have been expanded to all files in `tests/phpunit/`.
- Coding Standards: Sniffs against native PHP functions for filesystem interaction have been excluded for files in `tests/phpunit/`.
- To make PHPUnit testing `AspireUpdate\Debug` consistent and easier.
- To prevent coding standards errors and warnings for common and legitimate use in tests.
See #216
By opening this pull request, I do agree to abide by the [Code of …

Tests: Add test resources for `AspireUpdate\Debug`

---

includes/class-debug.php
tests/phpunit/tests/Debug/Debug_ReadTest.php

- Added tests for `Debug::read()`
- Some of these tests also cover `Debug::init_filesystem()`, `Debug::verify_filesystem()`, and `Debug::get_file_path()`.
- Ignored an untestable line from code coverage reports.
See #216

Add tests for `Debug::read()`

---

tests/phpunit/tests/Debug/Debug_ClearTest.php

- Added tests for `Debug::clear()`
- Some of these tests also cover `Debug::init_filesystem()`, `Debug::verify_filesystem()`, and `Debug::get_file_path()`.
See #216

Add tests for `Debug::clear()`

---

tests/phpunit/tests/Debug/Debug_LogTest.php

- Added tests for `Debug::log()`
- Some of these tests also cover `Debug::init_filesystem()`, `Debug::verify_filesystem()`, and `Debug::format_message()`.
See #216

Add tests for `Debug::log()`

---

tests/phpunit/tests/Debug/Debug_LogStringTest.php

Added tests for `Debug::log_string()`
See #216

Add tests for `Debug::log_string()`

---

tests/phpunit/tests/Debug/Debug_LogRequestTest.php

Added tests for `Debug::log_request()`
See #216

Add tests for `Debug::log_request()`

---

tests/phpunit/tests/Debug/Debug_LogResponseTest.php

Added tests for `Debug::log_response()`
See #216

Add tests for `Debug::log_response()`

---

includes/class-admin-settings.php

This should be tested with E2E tests instead.
Ignored `Admin_Settings::add_settings_field_callback()` from coverage reports.
To ensure this method doesn't unnecessarily affect coverage reports.
See #216 

Code Coverage: Ignore `Admin_Settings::add_settings_field_callback()`

---

.github/workflows/phpunit-tests.yml

The PHPUnit test workflow now installs Subversion before setting up the tests.
Subversion was removed from GitHub Actions' default packages for Ubuntu 24, which causes PHPUnit test setup to fail.
Fixes #253 

Workflows: Install SVN before running tests

---

.github/workflows/phpunit-tests.yml

The PHPUnit test workflow now performs a dummy run to prime the WordPress install for tests.
When this completes, the actual test run is performed, with the `WP_TESTS_SKIP_INSTALL` environment variable set to `1`.
Since many of the tests must run in separate processes, the WordPress installation occurs _in each process_. This is an unnecessary delay. By priming the install and explicitly disabling the install attempts in the actual runs, this delay is removed.
Also, it's nice to have nice things.
Fixes #257
By opening this pull request, I do agree to abide by the [Code of Conduct](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CODE_OF_CONDUCT.md) and be bound by the terms of the [Contribution Guidelines](https://github.com/aspirepress/.github/blob/updating-contribu …

Workflows: Prime a WP install and skip install for the actual test run.

---

includes/class-admin-settings.php

Changed the default API host from api.aspirecloud.org to api.aspirecloud.net
api.aspirecloud.org does not exist.  For usability and convenience, the default api host should point to the AspireCloud production server api.
Fixes #265 

change default API host from .org to .net

---

includes/class-api-rewrite.php
tests/phpunit/tests/API_Rewrite/APIRewrite_ConstructTest.php
tests/phpunit/tests/API_Rewrite/APIRewrite_PreHttpRequestTest.php

- Documented the new `$api_key` parameter of `API_Rewrite::__construct()`.
- Fixed tests broken by changes made in #268.
- Add a test to ensure the API key is added to the `Authorization` header.
- Missing documentation.
- Broken tests.
- Reduced code coverage.
See #268 

Follow up to #268

---

includes/class-admin-settings.php
includes/class-controller.php
tests/phpunit/includes/AdminSettings_UnitTestCase.php
tests/phpunit/tests/AdminSettings/AdminSettings_AdminNoticesTest.php
tests/phpunit/tests/AdminSettings/AdminSettings_RegisterAdminMenuTest.php
tests/phpunit/tests/AdminSettings/AdminSettings_ResetSettingsTest.php
tests/phpunit/tests/AdminSettings/AdminSettings_UpdateSettingsTest.php

- Added capability checks to the following methods:
- `Admin_Settings::reset_settings()` - Tests included.
- `Admin_Settings::admin_notices()` - Tests included.
- `Admin_Settings::update_settings()` - Tests included.
- `Controller::clear_log()` - Tests not possible as the underlying code terminates execution.
- `Controller::read_log()` - Tests not possible as the underlying code terminates execution.
- Updated `AdminSettings_UnitTestCase` to:
- add `$admin_id` and `$editor_id` properties for use in AdminSettings tests.
- set the user to `$admin_id` by default. (Most tests need this).
- Updated existing tests to:
- set the user to `$editor_id` where necessary (only a few tests need this).
- grant super admin where necessary (only a few tests need this).
To harden the plugin.
Fixes #277
By …

Add capability checks

---

composer.json
composer.lock
phpunit.xml.dist
tests/phpunit/bootstrap.php
tests/phpunit/includes/FilesystemDirect_UnitTestCase.php
tests/phpunit/multisite.xml
tests/phpunit/tests/API_Rewrite/APIRewrite_ConstructTest.php
tests/phpunit/tests/AdminSettings/AdminSettings_ConstructTest.php
tests/phpunit/tests/AdminSettings/AdminSettings_GetSettingTest.php
tests/phpunit/tests/Branding/Branding_AdminEnqueueScriptsTest.php
tests/phpunit/tests/Branding/Branding_ConstructTest.php
tests/phpunit/tests/Controller/Controller_ConstructTest.php
tests/phpunit/tests/FilesystemDirect/FilesystemDirect_GetContentsArrayTest.php
tests/phpunit/tests/FilesystemDirect/FilesystemDirect_PutContentsTest.php
tests/phpunit/tests/PluginsScreens/PluginsScreens_ConstructTest.php
tests/phpunit/tests/ThemesScreens/ThemesScreens_AdminEnqueueScriptsTest.php
tests/phpunit/tests/ThemesScreens/ThemesScreens_ConstructTest.php

- Changed mistaken `@string` annotations to `@param string` in some test docblocks.
- Prefixed the `Filesystem_Direct` test classes and files with `FilesystemDirect_`.
- Fixed a minor typo in one of the test docblocks.
- Fixed the `AdminSettings_ConstructTest::data_hooks_and_methods()` data provider dataset `admin_init -> update_settings` to pass `update_settings` as intended.
- Added calls to parent `set_up_before_class()`, `set_up()` or `tear_down()` methods in several test classes.
- Abstracted the shared fixtures for the `Filesystem_Direct` tests to `FilesystemDirect_UnitTestCase`.
- Fixed the path to the multisite configuration file in `composer.json`.
- Disabled path coverage by default.
- Excluded untested files from coverage reports.
- Configured dedicated site type coverage …

Test fixes and improvements

---

.github/workflows/generate-pot-pr.yml

Change workflow to run on tagging, not on branch push to `main`.
Fixes #288 
Too many runs of the workflow when not necessary. Now we will only run when a release is tagged.
n/a

288 [Bug]: Change Generate POT workflow to run only on tagging

---

includes/class-api-rewrite.php
tests/phpunit/tests/API_Rewrite/APIRewrite_PreHttpRequestTest.php

Add Accept JSON header if the request is not for downloading a file.
1) Add Accept JSON header if the request is not for downloading a file. 
2) Split the rewrite function for easy test-ability.
#274 

Add Accept JSON header if the request is not for downloading a file.

---

composer.lock
vendor/afragen/autoloader/Autoloader.php
vendor/afragen/autoloader/CHANGES.md
vendor/afragen/autoloader/composer.json

Bumps afragen/autoloader dependency to 3.0.1.  This silences a minor deprecation warning from php 8.4.
Future-proofing.
none.

build: update to afragen/autoloader 3.0.1

---

includes/class-admin-settings.php

Create settings link for the plugin in the plugin listing page
Add settings link for the plugin in the plugin listing page for ease of use
#295 

Create settings link for the plugin in the plugin listing page

---

includes/class-api-rewrite.php
tests/phpunit/tests/API_Rewrite/APIRewrite_PreHttpRequestTest.php

- A `WP_Error` object is returned when the request performed by `API_Rewrite::pre_http_request()` returns a non-200 HTTP response.
- A PHPUnit test has been added to verify and protect this behaviour going forward.
When the API request failed, the failed response was passed to admin pages, causing PHP warnings. This handles the errors as they should be handled.
Fixes #294 

API_Rewrite: Return `WP_Error` object for non-200 responses.

---

includes/class-api-rewrite.php
tests/phpunit/tests/API_Rewrite/APIRewrite_PreHttpRequestTest.php

- `WP_Error` is now returned for all response codes that aren't `200` or `404`.
- Tests have been added to ensure that `200` and `404` are the only codes that don't return a `WP_Error`.
When an installed plugin isn't available at the API, such as a third-party plugin or a custom plugin, a 404 is returned.
This was previously producing an error on the `Plugins -> Installed Plugins` screen, and shouldn't have been.
Fixes #294 
By opening this pull request, I do agree to abide by the [Code of Conduct](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CODE_OF_CONDUCT.md) and be bound by the terms of the [Contribution Guidelines](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CONTRIBUTING.md) in effect on the date and time of my contribution as …

Return `WP_Error` for all response codes that aren't `200` or `404`.

---

includes/class-api-rewrite.php
tests/e2e/admin-settings/api_host.spec.ts
tests/e2e/admin-settings/api_host_other.spec.ts
tests/e2e/admin-settings/api_key.spec.ts
tests/e2e/admin-settings/debug_request.spec.ts
tests/e2e/admin-settings/debug_response.spec.ts
tests/e2e/admin-settings/debug_string.spec.ts
tests/e2e/admin-settings/disable_ssl.spec.ts
tests/e2e/admin-settings/enable.spec.ts
tests/e2e/admin-settings/enable_debug.spec.ts

- Added missing textdomain to `__()` call in `API_Rewrite::pre_http_request()`.
- Abstracted passthrough response codes to an array.
- Fixed some formatting inconsistencies in E2E test files.
- i18n
- Reduced maintenance
- Consistency.
Fixes #303 

Several tidy ups

---

includes/class-api-rewrite.php
tests/phpunit/tests/API_Rewrite/APIRewrite_ConstructTest.php

- Added a check to ensure API rewriting is enabled before hooking `'pre_http_request'`.
- Adjusted an existing `API_Rewrite` test to enable API rewriting.
- Added an `API_Rewrite` test to check that the hook is not added when API rewriting is disabled.
The filter should only be applied when API rewriting is enabled.
This was causing errors on several screens when API rewriting was disabled.
Fixes #305
By opening this pull request, I do agree to abide by the [Code of Conduct](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CODE_OF_CONDUCT.md) and be bound by the terms of the [Contribution Guidelines](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CONTRIBUTING.md) in effect on the date and time of my contribution as proven by the revision …

API_Rewrite: Only filter `'pre_http_request'` when API rewriting is enabled

---

includes/class-admin-settings.php
includes/views/page-admin-settings.php

- Added `aria-describedby` to settings elements and a matching `id` attribute to the `.description` element.
- Added the `label_for` argument to `add_settings_field()` calls to ensure the field labels are wrapped in the `<label>` tags.
- Changed `Clear Log` and `View Log` from `a` elements to `button` elements with `type="button"` so they don't trigger a form submit.
- To reduce accessibility errors.
- To be more consistent with other settings pages in WordPress.
- **Note**: There are still 3 errors.
- An error due to `api_host_other` not having a label.
- A contrast error for the transparent text in the "Generate API Key" button
- A contrast error for Voltron.
Fixes #299 
By opening this pull request, I do agree to abide by the [Code of …

Admin_Settings: Various accessibility improvements

---

includes/class-admin-settings.php
includes/views/page-admin-settings.php
tests/e2e/data/routes.ts
tests/phpunit/tests/AdminSettings/AdminSettings_AdminEnqueueScriptsTest.php
tests/phpunit/tests/AdminSettings/AdminSettings_AdminNoticesTest.php
tests/phpunit/tests/AdminSettings/AdminSettings_RegisterAdminMenuTest.php

This moves the admin settings to the Settings menu.
The previous location in the Dashboard menu was uncommon and could lead to confusion for users.
Fixes #210

Move Admin Settings to the Settings menu

---

includes/class-admin-settings.php
includes/class-debug.php
tests/phpunit/tests/Debug/Debug_ClearTest.php

1) Randomize Log File Name
2) Delete the Log file instead of just clearing the contents when the clear log option is used. 
3) Delete the log file when the Debug mode changes from On to Off
The Debug file name being easily guessable and potentially publicly accessible on unsecured servers will cause a security risk.
Now the Debug file name is randomized and changed each time its cleared or the debug mode toggled.
Fixes #201 
By opening this pull request, I do agree to abide by the [Code of Conduct](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CODE_OF_CONDUCT.md) and be bound by the terms of the [Contribution Guidelines](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CONTRIBUTING.md) in effect on the date and time of my contribution as …

Randomize Log File Name

---

assets/js/aspire-update.js
includes/class-admin-settings.php

1) Fix Validation Issue when Other option is not selected
2) Add Validation Message
Validation Issue when Other option is not selected
Fixes #311 

Fix Validation Issue

---

.github/workflows/releases.yml

Update to releases workflow. Added permissions and attestation.
Seems the workflow requires additional permissions not in current repo settings.
Hopefully it now runs and completes.

update releases workflow

---

.github/workflows/generate-pot-pr.yml

Therefore doesn't work when triggered on the tag.
https://github.com/aspirepress/aspireupdate/actions/runs/13507397017/job/37741272037

The generate-pot workflow requires the branch name

---

.gitattributes

- Corrected `.package.json` to `package.json`.
- Corrected `.package-lock.json` to `package-lock.json`.
These files are not prefixed with `.`
Fixes #345

Build: Correct `package.json` paths.

---

includes/class-api-rewrite.php

Changed
```php
/* translators: %s: The response message. */
```
to
```php
/* translators: %s: The error message. */
```
Translator comments for the same string must be consistent.
Fixes #346 

I18N: Make the "Request Failed" comment consistent.

---

README.md
composer.json

* Package name changed from aspire-update to aspireupdate 
* Made changelog section in README a pointer to the CHANGES.md file
* Removed misleading info about api keys, which don't need to be documented yet (only admins need keys)
Roots Bedrock needs the package name to match the slug, otherwise an update ends up with two installs, one with the dash and one without. 
None I can find.
By opening this pull request, I do agree to abide by the [Code of Conduct](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CODE_OF_CONDUCT.md) and be bound by the terms of the [Contribution Guidelines](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CONTRIBUTING.md) in effect on the date and time of my contribution as proven by the revision information in …

Fix package name, update README

---

README.md
assets/js/aspire-update.js
includes/class-admin-settings.php
includes/class-api-rewrite.php
tests/e2e/admin-settings/compatibility.spec.ts
tests/e2e/admin-settings/skip_rewriting_on_existing_response.spec.ts
tests/e2e/data/fields.ts
tests/phpunit/tests/API_Rewrite/APIRewrite_PreHttpRequestTest.php

- Added a new checkbox option, `skip_rewriting_on_existing_response`.
- Added a new constant, `AP_COMPATIBILITY`.
- Added a guard to return an existing `$response` in `API_Rewrite::pre_http_request()` if `$response` is not `false` and the `skip_rewriting_on_existing_response` option is enabled.
- Added E2E and PHPUnit tests. This includes fixing existing tests to replace an erroneous default `[]` `$response` value with `false`.
- Added the `AP_COMPATIBILITY` constant to `README.md`.
If another plugin has filtered the default host and supplied a non-`false` response, we should not replace that response unless the user has told us to. The new option gives the user control over whether an existing response is respected, or overridden.
Fixes #358 
By opening this pull request, I do agree to …

Conditionally skip API rewriting

---

includes/class-api-rewrite.php

This ensures the filter is added and removed when expected.
- Added `PHP_INT_MAX` as the `$priority` before and after the rewritten request in `API_Rewrite::pre_http_request()`.
To ensure the hooked callback is added and removed when expected.
Fixes #365 

API_Rewrite: Specify hook priority in all  `*_filter()` calls.

---

.github/workflows/phpunit-tests.yml

The PHPUnit tests workflow previously ran against PHP 7.4 and 8.3. It now runs against PHP 7.4 and PHP 8.4.
The latest version of PHP is 8.4.
Fixes #373 

Workflows: Run PHPUnit tests against PHP 8.4.

---

includes/class-branding.php

- The "Learn more" text in the branding notice now reads "Learn about AspireUpdate".
Before:
After:
- To avoid conflicts with other link texts.
See #379 

Branding: Change "Learn more" to "Learn about AspireUpdate".

---

assets/js/aspire-update.js
includes/class-admin-settings.php

- The "Generate API Key" button now has a visual label.
- The label uses the value previously used in the button's `title` attribute.
- The button's `title` attribute has now been removed.
Before:
After:
The "Generate API Key" button was previously only labelled using a `title` attribute, which does not appear in many contexts, including touch interfaces and some browser configurations.
See #379 
By opening this pull request, I do agree to abide by the [Code of Conduct](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CODE_OF_CONDUCT.md) and be bound by the terms of the [Contribution Guidelines](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CONTRIBUTING.md) in effect on the date and time of my contribution as proven by the revision …

Admin_Settings: Use a visual label for the "Generate API Key" button.

---

assets/css/aspire-update.css
assets/images/icon-key.svg
assets/js/aspire-update.js
includes/class-admin-settings.php

Field labels have been changed to be more topical:
- **Enable AspireUpdate API Rewrites** -> **API Rewriting**
- **Enable Debug Mode** -> **Debug Mode**
- **Enable Debug Type** -> **Log Contents**
- **Disable SSL Verification** -> **SSL Verification**
Grouped fields, such as **Compatibility** and **Log Contents** have been wrapped in a container element which associates the group with the label.
Field descriptions have either been modified, or removed.
- The descriptions for the following fields have been removed as checkbox labels are sufficient:
- **API Rewriting**
- **Compatibility**
- **Debug Mode**
- **Log Contents**
- **SSL Verification**
- **API Host**: The description will now only display when "Other" has been selected.
- The description has been changed from "Your new API Host. …

Admin_Settings: Improve labels, descriptions and notice placement.

---

assets/css/aspire-update.css
includes/class-branding.php
tests/phpunit/tests/Branding/Branding_AddAdminBarMenuTest.php
tests/phpunit/tests/Branding/Branding_AdminEnqueueScriptsTest.php

- An admin bar menu has been added.
- This displays the current API host value.
- If the user has the appropriate capabilities, a link to the settings menu is included.
- If the `AP_REMOVE_UI` constant is set to `true`, the admin bar menu is not displayed.
- The stylesheet will be enqueued on all screens when in the administration area instead of just on certain screens.
- Tests for `Branding::admin_enqueue_scripts()` have been updated to account for this.
- Includes tests for the new `Branding::add_admin_bar_menu()` method.
To add a more subtle way to indicate the API host status.
See #379
By opening this pull request, I do agree to abide by the [Code of Conduct](https://github.com/aspirepress/.github/blob/updating-contributor-policy/CODE_OF_CONDUCT.md) and be bound by the terms of the …

Branding: Add an admin bar menu

---

README.md
includes/class-api-rewrite.php
tests/phpunit/tests/API_Rewrite/APIRewrite_PreHttpRequestTest.php

This disables by default adding the cachebuster string to the query unless `AP_DEBUG_BYPASS_CACHE` is set and truthy.  There is no admin UI to enable it, and I don't anticipate ever needing one.
We want to control the query caching behavior on AC's end now.  POST requests aren't going to be cached anyway.
none

tweak: disable cache busting unless AP_DEBUG_BYPASS_CACHE is set
